name: Auto-update JDK Catalog

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  auto-update-catalog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download and process Foojay data
        run: |
          .github/scripts/process-catalog.sh new_catalog.json

      - name: Compare with current catalog.json
        id: main_diff
        run: |
          result=$(.github/scripts/compare-catalog.sh catalog.json new_catalog.json)

          echo "identical=$result" >> $GITHUB_OUTPUT

      - name: Find latest open auto-update PR
        id: find_pr
        if: steps.main_diff.outputs.identical == 'false'
        run: |
          gh pr list --label "auto-update" --state open --json number,headRefName,createdAt \
            --jq 'sort_by(.createdAt) | reverse | .[0] // {}' > pr.json

          echo "pr_number=$(jq -r '.number // ""' pr.json)" >> $GITHUB_OUTPUT
          echo "pr_branch=$(jq -r '.headRefName // ""' pr.json)" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Checkout branch from latest PR and compare catalogs
        if: steps.find_pr.outputs.pr_number != ''
        id: pr_diff
        run: |
          git fetch origin ${{ steps.find_pr.outputs.pr_branch }}:${{ steps.find_pr.outputs.pr_branch }}
          git checkout ${{ steps.find_pr.outputs.pr_branch }}

          result=$(.github/scripts/compare-catalog.sh catalog.json new_catalog.json)

          echo "identical=$result" >> $GITHUB_OUTPUT

      - name: Update catalog, create branch and push
        if: steps.main_diff.outputs.identical == 'false' || steps.pr_diff.outputs.identical == 'false'
        run: |
          # Ensure we are on the main branch
          git checkout main

          # Make our workflow action a git user 
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Update existing catalog
          cp new_catalog.json catalog.json

          # Commit
          branch="auto/update-catalog-$(date +%s)"
          git checkout -b "$branch"
          git add catalog.json
          git commit -m "Auto-update catalog.json"

          # Push
          git push origin "$branch"

          echo "branch_name=$branch" >> $GITHUB_ENV

      - name: Create PR
        if: env.branch_name != ''
        run: |
          today=$(date +'%Y-%m-%d')

          gh pr create \
            --title "Auto-update JDK catalog $today" \
            --body "Automated update from workflow" \
            --head "$branch" \
            --base main \
            --label "auto-update"
        env:
          GH_TOKEN: ${{ github.token }}
