name: Release JDK Catalog

on:
  push:
    branches: [ main ]
    paths:
      - 'catalog.json'
  workflow_dispatch:

jobs:
  release-catalog:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine next version
        id: version
        run: |
          version=$(.github/scripts/next-version.sh)

          echo "Computed version: $version"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: JReleaser assemble
        uses: jreleaser/release-action@v2
        env:
          JRELEASER_PROJECT_VERSION: ${{ steps.version.outputs.version }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: 'assemble'

      - name: JReleaser full-release
        uses: jreleaser/release-action@v2
        env:
          JRELEASER_PROJECT_VERSION: ${{ steps.version.outputs.version }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
